global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

api:
  dashboard: true  # true by default
  insecure: true  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
#   Redirect to HTTPS
#   ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

  web-external:
    address: :81
    #   Redirect to HTTPS
    #   ---
    http:
      redirections:
        entryPoint:
          to: websecure-external
          scheme: https

  websecure-external:
    address: :444


# Configure your CertificateResolver here...
# ---
certificatesResolvers:
  cloudflare:
    acme:
      email: vladstefan.petre@outlook.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  aduh-ext:
    acme:
      email: vladstefan.petre@outlook.com
      storage: /etc/traefik/acme-aduh-ext.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: websecure
      tlsChallenge: { }

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Default is true
    network: hlel
#  file:
#    # watch for dynamic configuration changes
#    directory: /etc/traefik
#    watch: true

log:
  level: INFO